<a href="https://colab.research.google.com/github/Shahid1993/pytorch-notebooks/blob/master/00_PyTorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import torch

In [4]:
a = np.array(1)
b = torch.tensor(1)

print(a)
print(b)

1
tensor(1)


In [5]:
type(a), type(b)

(numpy.ndarray, torch.Tensor)

# Mathematical Operations

In [11]:
a = torch.tensor(4)
b = torch.tensor(2)

print(a, b)

tensor(4) tensor(2)


In [12]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

tensor(6)
tensor(2)
tensor(8)
tensor(2)


# Matrix Initialization

In [14]:
a = torch.zeros(3, 3)
print(a)
print(a.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.Size([3, 3])


In [15]:
torch.manual_seed(42)
a = torch.randn(3, 3)

a

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]])

# Matrix Operations

In [16]:
torch.manual_seed(42)
a = torch.randn(3, 3)
b = torch.randn(3, 3)

print(a)
print(b)

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]])
tensor([[ 0.2674,  0.5349,  0.8094],
        [ 1.1103, -1.6898, -0.9890],
        [ 0.9580,  1.3221,  0.8172]])


In [24]:
# matrix addition
print(torch.add(a,b), '\n')

# matrix subtraction
print(torch.sub(a,b), '\n')

# matrix multiplication (similar to dot product in numpy)
print(torch.mm(a, b), '\n')

# matrix division
print(torch.div(a, b))

# matrix transpose
print(torch.t(a))

tensor([[ 0.6040,  0.6637,  1.0438],
        [ 1.3406, -2.8127, -1.1753],
        [ 3.1662,  0.6841,  1.2788]]) 

tensor([[ 0.0693, -0.4061, -0.5749],
        [-0.8800,  0.5669,  0.8026],
        [ 1.2502, -1.9601, -0.3555]]) 

tensor([[ 0.4576,  0.2724,  0.3367],
        [-1.3636,  1.7743,  1.1446],
        [ 0.3243,  2.8696,  2.7954]]) 

tensor([[ 1.2594,  0.2408,  0.2897],
        [ 0.2075,  0.6645,  0.1884],
        [ 2.3051, -0.4826,  0.5649]])
tensor([[ 0.3367,  0.2303,  2.2082],
        [ 0.1288, -1.1229, -0.6380],
        [ 0.2345, -0.1863,  0.4617]])


# Concatenating Tensors

In [25]:
a = torch.tensor([[1,2], [3,4]])
b = torch.tensor([[5,6], [7,8]])

print(a, '\n')
print(b)

tensor([[1, 2],
        [3, 4]]) 

tensor([[5, 6],
        [7, 8]])


In [28]:
# concatenating vertically
print(torch.cat((a, b)), '\n')

# concatenating horizontally
print(torch.cat((a,b), dim=1))

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]) 

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


# Reshaping Tensors

In [29]:
torch.manual_seed(42)
a = torch.randn(2, 4)

print(a)
print(a.shape)

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380]])
torch.Size([2, 4])


In [31]:
# reshaping tensor
b = a.reshape(1,8)
print(b)

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229, -0.1863,  2.2082, -0.6380]])


In [33]:
a = np.array([[1,2], [3,4]])
print(a)

# converting the numpy array to tensor
b = torch.from_numpy(a)
print(b)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])


Common PyTorch Modules
===

## Autograd Module
- **PyTorch uses a technique called automatic differentiation.** It records all the operations that we are performing and replays it backward to compute gradients. This technique helps us to save time on each epoch as we are calculating the gradients on the forward pass itself.
- Specifying `requires_grad` as `True` will make sure that the gradients are stored for this particular tensor whenever we perform some operation on it.
- We perform the following operations on a:  
b = a + 5  
c = mean(b) = Σ(a+5) / 4  
Now, the derivative of c w.r.t. a will be ¼ and hence the gradient matrix will be 0.25. 

In [50]:
# Initializing a tensor
a = torch.ones(2,2,requires_grad=True)

print(a)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [51]:
# performing operations on tensor
b = a+5
c = b.mean()

print(b, c)

tensor([[6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>) tensor(6., grad_fn=<MeanBackward0>)


In [52]:
# back propagating
c.backward()

# computing gradients
print(a.grad)

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])
